In [ ]:
!pip install pandas

In [ ]:
!pip install kaggle

In [ ]:
!pip install kaggle api

In [ ]:
from datetime import date
import time

In [1]:
import pandas as pd 
from kaggle.api.kaggle_api_extended import KaggleApi

api = KaggleApi()
api.authenticate()

print("Kaggle API connected successfully")

Kaggle API connected successfully

In [2]:
api.dataset_download_files(
    'najir0123/walmart-10k-sales-datasets',
    path='./data',
    unzip=True
)

print("Successfully imported")

Dataset URL: https://www.kaggle.com/datasets/najir0123/walmart-10k-sales-datasets
Successfully imported

In [3]:
df = pd.read_csv('data/Walmart.csv')
print('Datasets loaded successfully')

Datasets loaded successfully

In [4]:
print(df.head())

   invoice_id   Branch         City                category unit_price  \
0           1  WALM003  San Antonio       Health and beauty     $74.69
1           2  WALM048    Harlingen  Electronic accessories     $15.28
2           3  WALM067  Haltom City      Home and lifestyle     $46.33
3           4  WALM064      Bedford       Health and beauty     $58.22
4           5  WALM013       Irving       Sports and travel     $86.31

   quantity        date      time payment_method  rating  profit_margin
0       7.0  05-01-2019  13:08:00        Ewallet     9.1           0.48
1       5.0  08-03-2019  10:29:00           Cash     9.6           0.48
2       7.0  03-03-2019  13:23:00    Credit card     7.4           0.33
3       8.0  27-01-2019  20:33:00        Ewallet     8.4           0.33
4       7.0  08-02-2019  10:37:00        Ewallet     5.3           0.48

In [ ]:
df.columns

In [ ]:
df.shape

In [23]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [ ]:
df.to_csv('data/Walmart.csv', index=False)

In [5]:
df.duplicated().sum()

np.int64(51)

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [8]:
df.columns = df.columns.str.lower()

In [27]:
df

,invoice_id,branch,city,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,WALM056,Rowlett,Fashion accessories,$37,3.0,03/08/23,10:10:00,Cash,3.0,0.33
9996,9997,WALM030,Richardson,Home and lifestyle,$58,2.0,22/02/21,14:20:00,Cash,7.0,0.48
9997,9998,WALM050,Victoria,Fashion accessories,$52,3.0,15/06/23,16:00:00,Credit card,4.0,0.48
9998,9999,WALM032,Tyler,Home and lifestyle,$79,2.0,25/02/21,12:25:00,Cash,7.0,0.48
9999,10000,WALM069,Rockwall,Fashion accessories,$62,3.0,26/09/20,9:48:00,Cash,3.0,0.33

In [9]:
df['unit_price']=df['unit_price'].str.replace('$','').astype(float)

In [10]:
df['total_sale'] = df['unit_price']*df['quantity']
df

,invoice_id,branch,city,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total_sale
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05-01-2019,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08-03-2019,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03-03-2019,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27-01-2019,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08-02-2019,10:37:00,Ewallet,5.3,0.48,604.17
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,WALM056,Rowlett,Fashion accessories,37.00,3.0,03-08-2023,10:10:00,Cash,3.0,0.33,111.00
9996,9997,WALM030,Richardson,Home and lifestyle,58.00,2.0,22-02-2021,14:20:00,Cash,7.0,0.48,116.00
9997,9998,WALM050,Victoria,Fashion accessories,52.00,3.0,15-06-2023,16:00:00,Credit card,4.0,0.48,156.00
9998,9999,WALM032,Tyler,Home and lifestyle,79.00,2.0,25-02-2021,12:25:00,Cash,7.0,0.48,158.00
9999,10000,WALM069,Rockwall,Fashion accessories,62.00,3.0,26-09-2020,09:48:00,Cash,3.0,0.33,186.00

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10000 non-null  int64
 1   branch          10000 non-null  str
 2   city            10000 non-null  str
 3   category        10000 non-null  str
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            10000 non-null  str
 7   time            10000 non-null  str
 8   payment_method  10000 non-null  str
 9   rating          10000 non-null  float64
 10  profit_margin   10000 non-null  float64
 11  total_sale      9969 non-null   float64
dtypes: float64(5), int64(1), str(6)
memory usage: 937.6 KB

In [18]:
df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')

In [17]:

# convert time column
df['time'] = pd.to_datetime(df['time'], format='%H:%M:%S').dt.time

In [30]:
!pip install mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector-python in C:\Users\Shubham\AppData\Roaming\Python\Python313\site-packages (9.7.0)

In [31]:
!pip install sqlalchemy pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in C:\Users\Shubham\AppData\Roaming\Python\Python313\site-packages (2.0.50)
Requirement already satisfied: pymysql in C:\Users\Shubham\AppData\Roaming\Python\Python313\site-packages (1.2.0)
Requirement already satisfied: greenlet>=1 in C:\Users\Shubham\AppData\Roaming\Python\Python313\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Shubham\AppData\Roaming\Python\Python313\site-packages (from sqlalchemy) (4.15.0)

In [38]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="spatil123",
    database="sales"
)

print("Connected Successfully")

Connected Successfully

In [44]:
import pymysql 
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:spatil123@localhost:3306/sales"
)

print("Connected Successfully")

Connected Successfully

In [45]:
df.to_sql(
    name='walmart_data',
    con=engine,
    if_exists='append',
    index=False
)

print("Data Loaded Successfully")

Data Loaded Successfully